version: '3.3'
services:
  api-users: 
    container_name: api-users  
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: server-builder
    ports:
      - '${HOST_SERVER_PORT}:${SERVER_PORT}'   
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    user: node
    env_file:
      - .env
    networks:
      - api-users
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '${MONGODB_LOCAL_PORT}:${MONGODB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/var/lib/mongodb/data    
    networks:
      - api-users

networks:
  api-users:
  
volumes:
  mongodb_data: